### ISSUE TITLE
about page link not formed correctly in some cases

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#10]
https://www.raymondmaine.org/community-resources/panther-pond-association → https://www.raymondmaine.org/community-resources/panther-pond-associationcontentabout-ppa

https://www.hhsyc.org → https://www.hhsyc.org/http:hhsyc.orgAbout_HHSYCAboutUs.html

http://www.mythsandfacts.com → http://www.mythsandfacts.com/http:www.mythsandfacts.orgcontentabout.asp

Looks like this might be a case of absolute links vs relative links not being recognized correctly.

**Comment by milandv** [comment]
Ah. Looks like this might relate to issue #7 which i think was merged in but may have been reverted?

**Comment by jaeyk** [comment]
@milandv It seems the old solution didn't really resolve this issue and found that there's an easier solution to fix it. I will push a commit by tomorrow.

**Comment by milandv** [comment]
(Also, one other small thing. for the case where we're combining the href with base, we should maybe just strip the leading / from the href so that combining: https://some.site.org/ + /page/about/us → https://some.site.org/page/about/us and not https://some.site.org/pageaboutus)

**Comment by jaeyk** [comment]
@milandv Fixed both problems (relative path and base case path formation) with the new issue.
