### ISSUE TITLE
pages with unverified server certificate are failing

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#16]
example: read_html("http://albersfoundation.org/") → Error in open.connection(x, "rb") : 
  server certificate verification failed. CAfile: none CRLfile: none

this is the same result as httr::GET("http://albersfoundation.org/")

read_html doesn't take CURL options but httr does so I think the solution here is:

`pg <- read_html(content(GET(base_url, config(ssl_verifypeer=FALSE, timeout=10,followlocation=TRUE)))`

This makes that page readable. BUT also need to change the options on url.exists to match. so:

`url.exists("http://albersfoundation.org/", .opts = list(ssl.verifypeer=FALSE, timeout=10,followlocation=TRUE))`

[This has the added advantage of building in a timeout so we'd no longer need that in the ETL code.]

**Comment by milandv** [comment]
(maybe should also add a user agent to that call)

**Comment by milandv** [comment]
At this point I'm just liveblogging in the issue comments which is bad form but … another option is not to use url.exists and instead to run HEAD(base_url) with the same options and see if it returns a code that works. 

Saying that in part because of this url: https://www.nutleyrescue.org/

Which url.exists() returns FALSE for but which read_html (or read_html wrapped around GET) has no problem with.

**Comment by milandv** [comment]
Here's a function that checks if a URL exists using only httr: https://stackoverflow.com/questions/52911812/check-if-url-exists-in-r

And could modify that to add curl configuration so that it's:

`res <- sHEAD(x, config(ssl_verifypeer=FALSE, timeout=10,followlocation=TRUE), ...)`

and 

`res <- sGET(x, config(ssl_verifypeer=FALSE, timeout=10,followlocation=TRUE), ...)`

**Comment by jaeyk** [comment]
I will take a look at this tomorrow (3/17).
