### ISSUE TITLE
extract_about_links failing when there is an about link

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#2]
extract_about_links("http://www.saltpondscoalition.org/") is returning no about page when there is one in the html

I _think_ the problem is in `if_not_about`

This returns FALSE
`TRUE %in% href %>% tolower() %>% str_detect("about")`

These both return TRUE
`TRUE %in% (href %>% tolower() %>% str_detect("about"))`

`any(href %>% tolower() %>% str_detect("about")==TRUE)`

for that example

**Comment by milandv** [comment]
This is specifically for tree search

**Comment by jaeyk** [comment]
@milandv Both problem identification and solution are spot-on. I fixed it and also added unit testing for this problem.
