### ISSUE TITLE
php filter too stringent in GetAboutPages::extract_about_links

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#3]
example: http://www.egacademyfoundation.org/index.html

There's one link on the page to some Facebook post that hits a PHP page (because Facebook is programmed in PHP). The rest of the links are not though. 

`TRUE %in% str_detect(href, ".php") == TRUE` gives a "PHP error" is any link is a PHP page so it's missing the about page link. 

[More generally, do we need the PHP error? what happens if a page has about.php?]

**Comment by jaeyk** [comment]
I will work on this tomorrow afternoon.

**Comment by jaeyk** [comment]
@milandv I decided to remove the PHP error. Excellent point. I will commit the change shortly.
