### ISSUE TITLE
GetAboutPages::extract_about_links should return a list filtered to distinct href

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#4]
Right now we're doing distinct combinations of href and link text but that means we're getting the same url returned multiple times with slightly different texts. 

So for instance, http://saltpondscoalition.org is returning:

# A tibble: 4 x 3
  href         link_text    link                                      
  <chr>        <chr>        <glue>                                    
1 AboutUs.html "ABOUT US"   http://saltpondscoalition.org/AboutUs.html
2 AboutUs.html "WHO WE ARE" http://saltpondscoalition.org/AboutUs.html
3 AboutUs.html ""           http://saltpondscoalition.org/AboutUs.html
4 AboutUs.html "Who We Are" http://saltpondscoalition.org/AboutUs.html
> 
Which is the same link four times.

**Comment by jaeyk** [comment]
@milandv So your view is at least in terms of the return output we should drop href? (usually, it's very redundant).

**Comment by milandv** [comment]
drop duplicate hrefs, yes. the link text doesn't matter that much (since we're going to grab the page content anyway) so if we kept just the first row of that we'd have all we need. Downstream we don't actually want to hit that AboutUs.html url four times because we recorded it once for each link text.

**Comment by jaeyk** [comment]
Drop the seond col of the return data frame and grab the unique value of the third column would solve this. Thanks for the catch!
