### ISSUE TITLE
[tier 2] Some sites use "Who We Are" instead of "About" or "About Us"

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#5]
can't do everything in this iteration so this is tier 2 but for future enhancement noting that some websites have their about page content on a page called "Who We Are" with an href that matches that. 

Example: https://www.tomorrowfund.org/who-we-are

In the future we could add code to support that.

**Comment by jaeyk** [comment]
Excellent. This is also one of the things we should have in the wiki. So, the wiki can serve two goals: documentation and roadmap. Changelog of the pkg would also help.

**Comment by jaeyk** [comment]
The new commit fixed this issue by varying possible URL types. See the example below.

```r
  possible_about_urls <- c(glue("{base_url}about-us"), # About case 1
                           glue("{base_url}about"), # About case 2 
                           glue("{base_url}who-we-are")) # Who we are case 
```
I like this solution as it further modularizes the existing code. So, we just need to add a new character element if we need to deal with other edge cases. As usual, I also added unit testing for this issue.
