### ISSUE TITLE
link formatting off when page uses an absolute reference in link

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#7]
I don't have an example yet but I _think_ this is going to be an issue. When a page uses a relative reference to the about page (href="/about.html") then this line should be fine:

```
            mutate(href = str_replace_all(href, "/", "")) %>%
            mutate(link = glue("{base_url}{href}"))
```

but if they use an absolute reference (href="https://oursite.org/about.html") then it won't.

Will either create an example or find one and add it here.

**Comment by milandv** [comment]
Oh. guess I didn't have to look too far. Not a perfect example because we can guess the about page for this site but here's one that uses absolute references in links in general: https://front.moveon.org !

**Comment by milandv** [comment]
Maybe this is solved with a conditional [ ifelse ] with:

`str_detect(href, "http.{0,1}://")`

**Comment by jaeyk** [comment]
Hmn. @milandv When I tried this `get_about_page_content("https://front.moveon.org")`, I get the output. Did I miss something here?

**Comment by milandv** [comment]
Because it's guessing the about link correctly and not actually taking it from the page. If it were to take it from the page, though, it would get it wrong because of the absolute link. (It's an imperfect test case!)

so i'm suggesting something like:

```
              mutate(href = ifelse(str_detect(href, "http.{0,1}://"), href, str_replace_all(href, "/", ""))) %>%
              mutate(link = ifelse(str_detect(href, "http.{0,1}://"), href,glue("{base_url}{href}")))
```

**Comment by jaeyk** [comment]
@milandv I replaced the existing code with your suggestions. Seems the new code didn't break anything old. Good point. I will push this commit before the meeting (done; see the commit `b47cb35`). But I don't think that I fully understand this issue 😭. I want to hear from you about what matters here during the meeting.
