### ISSUE TITLE
Add timeout to prevent hanging on unreachable/very slow websites

### ISSUE THREAD

**Issue by milandv** [p3lab/GetAboutPages#9]
could do as an httr parameter for instance.

but at the moment i think the function hangs forever for a page it can't reach. (will add an example here.)

**Comment by milandv** [comment]
http://lungbanksofamerica.org/ is an example.

**Comment by jaeyk** [comment]
@milandv In terms of work productivity, does this mean GetAboutPages is our next target for data migration? I'm happy to look at this and other related cases this week.

**Comment by milandv** [comment]
Yes. Now that we have IRS text for 2019 (and can run text for 2020) we should populate the AboutPage text so that the machine learning can use both.

**Comment by milandv** [comment]
here's a suggestion on wrapping the read_html in GET from httr: https://stackoverflow.com/questions/48722076/how-to-set-timeout-in-rvest

**Comment by jaeyk** [comment]
@milandv I was thinking of a similar solution. It seems that `RCurl` is outdated. This is great!

**Comment by jaeyk** [comment]
Okay not adding new pkg dependencies. Sth like this may work: 

```r
if (url.exists(base_url, timeout = 10) == FALSE) { stop("This URL is not responding (10 seconds timeout).") }
```

Also, I'm gonna parameterize 10 instead of hard-coding.
